(() => {
'use strict';
const APP_VERSION='fitness-v6.1.0-high-knees-responsive-review';
const SCHEMA_VERSION=5;
const STORAGE_KEY='completeFitnessAppStateV4';
const OLD_STORAGE_KEY_V3='completeHealthAppStateV3';
const OLD_STORAGE_KEY_V2='completeHealthAppStateV2';
const MEDIA_CACHE='fitness-v6-1-high-knees-review-v1';
const EXERCISE_IDS=["march", "armCircles", "stepTouch", "hipCircles", "torsoTwist", "heelDigs", "kneeHugs", "ankleRolls", "squat", "sumoSquat", "squatPulse", "reverseLunge", "sideLunge", "curtsyLunge", "gluteBridge", "singleLegBridge", "calfRaise", "wallSit", "goodMorning", "donkeyKick", "fireHydrant", "inclinePushup", "pushup", "pikePress", "shoulderTap", "tricepsDip", "bentRow", "reverseFly", "floorPress", "superman", "plank", "sidePlank", "deadBug", "birdDog", "heelTap", "bicycle", "crunch", "lowJack", "highKnees", "skater", "mountainClimber", "fastFeet", "squatReach", "reverseLungeKnee", "burpeeStepback", "childPose", "catCow", "cobra", "hamstringStretch", "hipFlexorStretch", "chestOpener", "figure4", "thoracicRotation", "breathing", "downwardDog"];
const APPROVED_MEDIA=new Set(EXERCISE_IDS);
const GOALS={"general": {"label": "General fitness", "note": "Build balanced strength, stamina, mobility and consistency.", "steps": ["Train all major muscle groups", "Use moderate cardio", "Keep one recovery day"]}, "fat": {"label": "Reduce body fat", "note": "Combine consistent training, daily movement and a sustainable food pattern. Fat cannot be reduced from only one chosen body area.", "steps": ["Complete strength and cardio days", "Add regular walking", "Use repeatable portions, not crash diets"]}, "stamina": {"label": "Improve stamina", "note": "Progress gradually by moving longer while keeping breathing and technique controlled.", "steps": ["Start with low-impact intervals", "Increase work time slowly", "Record a monthly stamina test"]}, "shape": {"label": "Shape and tone body", "note": "Use controlled repetitions, full movement range and progressive resistance.", "steps": ["Prioritise legs, glutes, back and shoulders", "Slow the lowering phase", "Track waist and strength, not only weight"]}, "strength": {"label": "Build strength", "note": "Use reliable form and increase resistance or difficulty one step at a time.", "steps": ["Choose controlled variations", "Record repetitions or resistance", "Recover before repeating hard muscle work"]}, "mobility": {"label": "Improve mobility", "note": "Combine active movement, strength through comfortable ranges and gentle recovery work.", "steps": ["Move daily without forcing range", "Strengthen around stiff joints", "Use Day 7 for easy mobility"]}};
const DIET_LABELS={"indian": "Indian vegetarian", "lacto": "Vegetarian with dairy", "ovo": "Vegetarian with eggs", "lactoOvo": "Dairy + eggs", "vegan": "Vegan", "highProtein": "High-protein vegetarian"};
const STAGES=[
 {name:'Foundation',weeks:'Weeks 1–2',text:'Learn movement form, use easier options and establish a repeatable six-day rhythm.'},
 {name:'Control',weeks:'Weeks 3–4',text:'Improve balance, trunk control and consistent range of motion.'},
 {name:'Build',weeks:'Weeks 5–6',text:'Increase repetitions, work duration or light resistance while form remains reliable.'},
 {name:'Capacity',weeks:'Weeks 7–8',text:'Complete more total quality work and recover efficiently between intervals.'},
 {name:'Progression',weeks:'Weeks 9–10',text:'Use harder variations or slightly greater resistance one factor at a time.'},
 {name:'Consolidation',weeks:'Weeks 11–12',text:'Complete stronger full sessions, repeat fitness tests and plan the next cycle.'}
];
const DEFAULT_STATE={schema:SCHEMA_VERSION,profile:{name:'',ageRange:'30-39',height:'',weight:''},goal:'general',level:'beginner',equipment:'none',duration:60,theme:'system',sound:'on',autoplay:'on',reducedMotion:'off',diet:'indian',foodExclusions:'',currentDay:1,completedDays:[],workouts:[],checkins:[],tests:[],safetyAck:false,onboardingDone:false,readiness:'',activeSession:null,programStart:'',autoAdvance:'on',nextPreview:'on',orientation:'auto',startFocus:'off',updatedAt:'',deviceId:''};
function ex(name,category,muscles,benefit,steps,easier,harder,caution,animation){return{name,category,muscles,benefit,steps,easier,harder,caution,animation};}
function plan(day,title,focus,intensity,warmup,circuitA,circuitB,finisher,cooldown){return{day,title,focus,intensity,warmup,circuitA,circuitB,finisher,cooldown};}
function meals(day,focus,items){return{day,focus,items};}
const EXERCISES={
    march: ex('March in Place', 'warmup', ['Legs', 'Heart'], 'Raises body temperature and prepares joints for exercise.', ['Stand tall with ribs stacked over hips.', 'Lift one knee while swinging the opposite arm.', 'Land softly and keep a steady breathing rhythm.'], 'Use a slower pace and hold a wall.', 'Drive the knees higher and move the arms faster.', 'Do not lean backwards or stamp the feet.', 'march'),
    armCircles: ex('Arm Circles', 'warmup', ['Shoulders', 'Upper back'], 'Warms the shoulders and improves movement awareness.', ['Stand tall with arms extended.', 'Make small controlled circles, then gradually enlarge them.', 'Reverse direction halfway through.'], 'Keep the circles small.', 'Add a light squat while circling.', 'Avoid forcing painful shoulder range.', 'shoulder'),
    stepTouch: ex('Step Touch', 'warmup', ['Hips', 'Legs'], 'Gently raises heart rate and coordinates side-to-side movement.', ['Step one foot sideways.', 'Bring the other foot in lightly.', 'Repeat side to side with relaxed arm swings.'], 'Take smaller steps.', 'Add a deeper knee bend and larger arm swing.', 'Keep knees tracking over toes.', 'jack'),
    hipCircles: ex('Hip Circles', 'warmup', ['Hips', 'Core'], 'Lubricates the hip joints and prepares the trunk.', ['Stand with feet comfortably apart.', 'Move the hips in a slow circle.', 'Keep the chest tall and reverse direction.'], 'Make a smaller circle.', 'Add a gentle knee bend.', 'Do not force the lower back.', 'mobility'),
    torsoTwist: ex('Standing Torso Twist', 'warmup', ['Spine', 'Core'], 'Warms the trunk for rotational movement.', ['Stand tall with soft knees.', 'Rotate the rib cage gently from side to side.', 'Let the arms move naturally without forcing range.'], 'Keep hands on the chest and use a small range.', 'Add a controlled knee lift toward the opposite elbow.', 'Do not twist sharply through the knees.', 'twist'),
    heelDigs: ex('Heel Digs', 'warmup', ['Hamstrings', 'Calves'], 'Warms the back of the legs and ankles.', ['Tap one heel forward with toes lifted.', 'Sit the hips back slightly.', 'Alternate sides with easy arm pulls.'], 'Keep the heel closer to the body.', 'Move faster while staying light on the feet.', 'Do not lock the supporting knee.', 'march'),
    kneeHugs: ex('Alternating Knee Hug', 'warmup', ['Hips', 'Balance'], 'Mobilises the hips and practises single-leg balance.', ['Stand tall and lift one knee.', 'Gently draw it toward the chest.', 'Release slowly and change sides.'], 'Hold a wall and lift only to a comfortable height.', 'Rise onto the toes of the standing leg.', 'Avoid rounding the back to reach the knee.', 'balance'),
    ankleRolls: ex('Ankle Rolls', 'warmup', ['Ankles', 'Calves'], 'Prepares the ankles for squats, lunges and cardio.', ['Shift weight onto one leg while holding support if needed.', 'Lift the other foot slightly.', 'Circle the ankle slowly in both directions.'], 'Keep toes on the floor and circle the heel.', 'Balance without support.', 'Move slowly and avoid pain.', 'calf'),
    squat: ex('Bodyweight Squat', 'strength', ['Thighs', 'Glutes', 'Core'], 'Builds lower-body strength for standing, lifting and climbing.', ['Set feet about shoulder-width apart.', 'Sit hips down and back while knees track over toes.', 'Press through the whole foot to stand tall.'], 'Squat to a chair or use a smaller depth.', 'Add a slow three-second lowering phase or hold dumbbells.', 'Do not let knees collapse inward or heels lift.', 'squat'),
    sumoSquat: ex('Sumo Squat', 'strength', ['Inner thighs', 'Glutes'], 'Strengthens the hips and inner thighs through a wider stance.', ['Take a wide stance with toes turned slightly out.', 'Lower the hips while keeping the chest tall.', 'Squeeze the glutes as you stand.'], 'Use a shallow range and hold support.', 'Add a pulse at the bottom or hold a dumbbell.', 'Do not force the knees wider than the toes.', 'squat'),
    squatPulse: ex('Squat Pulse', 'strength', ['Thighs', 'Glutes'], 'Increases muscular endurance in the legs.', ['Lower into a comfortable squat.', 'Move up and down only a few centimetres.', 'Keep weight through the mid-foot and heel.'], 'Pulse higher or alternate with full standing.', 'Stay lower while maintaining alignment.', 'Stop if knees or lower back become painful.', 'squat'),
    reverseLunge: ex('Reverse Lunge', 'strength', ['Thighs', 'Glutes', 'Balance'], 'Builds leg strength and balance with less forward knee stress than many forward lunges.', ['Step one foot back and land on the ball of the foot.', 'Bend both knees while keeping the front foot planted.', 'Push through the front foot to return.'], 'Hold a wall and take a shorter step.', 'Add a knee drive or hold dumbbells.', 'Keep the front knee tracking over the middle toes.', 'lunge'),
    sideLunge: ex('Side Lunge', 'strength', ['Glutes', 'Inner thighs'], 'Strengthens side-to-side movement and hip control.', ['Step wide to one side.', 'Sit the hips back over the stepping leg while the other leg stays long.', 'Push the floor away to return to centre.'], 'Use a smaller side step.', 'Hold a dumbbell at chest height.', 'Keep the working heel down and chest lifted.', 'lunge'),
    curtsyLunge: ex('Curtsy Step-Back', 'strength', ['Glutes', 'Thighs'], 'Challenges hip control and glute endurance.', ['Step one foot diagonally behind the other.', 'Bend both knees only as far as comfortable.', 'Press through the front foot to stand.'], 'Use a normal reverse lunge instead.', 'Add a controlled knee lift on return.', 'Avoid twisting the front knee inward.', 'lunge'),
    gluteBridge: ex('Glute Bridge', 'strength', ['Glutes', 'Hamstrings', 'Core'], 'Strengthens the hips and supports better lifting mechanics.', ['Lie on your back with knees bent and feet planted.', 'Brace gently and squeeze the glutes to lift the hips.', 'Pause, then lower without over-arching the back.'], 'Lift only partway.', 'Use a single-leg variation or add a dumbbell across the hips.', 'Do not push from the neck or flare the ribs.', 'bridge'),
    singleLegBridge: ex('Alternating Bridge March', 'strength', ['Glutes', 'Core'], 'Builds hip stability while resisting trunk rotation.', ['Lift into a comfortable bridge.', 'Keep the pelvis level and lift one foot a few centimetres.', 'Set it down and alternate.'], 'Hold a normal bridge.', 'Straighten the lifted leg farther from the body.', 'Do not let one hip drop.', 'bridge'),
    calfRaise: ex('Calf Raise', 'strength', ['Calves', 'Ankles'], 'Improves ankle strength and walking or running efficiency.', ['Stand tall with feet parallel.', 'Rise smoothly onto the balls of the feet.', 'Pause and lower with control.'], 'Hold a wall and use both legs.', 'Use one leg or hold dumbbells.', 'Do not roll ankles outward.', 'calf'),
    wallSit: ex('Wall Sit', 'strength', ['Thighs', 'Glutes'], 'Builds lower-body endurance without repeated impact.', ['Place your back against a wall.', 'Slide down to a comfortable knee angle.', 'Press the back gently into the wall and breathe.'], 'Stay higher and hold for less time.', 'Hold a weight or alternate heel lifts.', 'Do not force a deep position if knees hurt.', 'wall'),
    goodMorning: ex('Hip Hinge / Good Morning', 'strength', ['Hamstrings', 'Glutes', 'Back'], 'Teaches safe bending and strengthens the posterior chain.', ['Stand tall with hands on hips or chest.', 'Soften knees and push hips backward while the spine stays long.', 'Squeeze glutes to return upright.'], 'Use a smaller hip movement.', 'Hold dumbbells or slow the lowering phase.', 'Do not round the lower back.', 'hinge'),
    donkeyKick: ex('Donkey Kick', 'strength', ['Glutes', 'Core'], 'Trains hip extension while the trunk stays stable.', ['Start on hands and knees.', 'Keep one knee bent and press the foot upward.', 'Stop before the lower back arches and lower slowly.'], 'Reduce the lift height.', 'Add a pause at the top or a resistance band.', 'Do not rotate the pelvis.', 'bird'),
    fireHydrant: ex('Fire Hydrant', 'strength', ['Side glutes', 'Core'], 'Strengthens the side glutes for knee and pelvic stability.', ['Start on hands and knees.', 'Lift one bent knee out to the side.', 'Keep the trunk still and lower with control.'], 'Lift only a few centimetres.', 'Add a resistance band above the knees.', 'Do not shift all body weight to one side.', 'bird'),
    inclinePushup: ex('Incline Push-Up', 'strength', ['Chest', 'Arms', 'Core'], 'Builds upper-body pushing strength with an adjustable difficulty.', ['Place hands on a stable wall, bench or counter.', 'Keep the body in one long line.', 'Lower the chest toward the support and press away.'], 'Use a higher wall position.', 'Use a lower surface or progress to the floor.', 'Do not let hips sag or elbows flare straight sideways.', 'pushup'),
    pushup: ex('Push-Up', 'strength', ['Chest', 'Arms', 'Core'], 'Strengthens the chest, shoulders, triceps and trunk.', ['Set hands slightly wider than shoulders.', 'Keep head, ribs, hips and legs aligned.', 'Lower with control and press the floor away.'], 'Use knees down or an incline.', 'Use a slower lowering phase or a pause near the floor.', 'Do not drop the hips or crane the neck.', 'pushup'),
    pikePress: ex('Pike Shoulder Press', 'strength', ['Shoulders', 'Arms'], 'Builds shoulder pushing strength using body weight.', ['Start with hips high and hands firmly planted.', 'Bend elbows and lower the head between the hands.', 'Press back to the starting position.'], 'Use a wall press with hips slightly back.', 'Elevate the feet carefully.', 'Keep elbows angled back rather than flared wide.', 'pushup'),
    shoulderTap: ex('Plank Shoulder Tap', 'core', ['Core', 'Shoulders'], 'Improves trunk stability while transferring weight between the arms.', ['Start in a high plank or hands-and-knees position.', 'Brace and lift one hand to tap the opposite shoulder.', 'Place it down quietly and alternate.'], 'Perform from hands and knees.', 'Use a full plank with feet closer together.', 'Do not let the hips rock side to side.', 'plank'),
    tricepsDip: ex('Chair Triceps Dip', 'strength', ['Triceps', 'Shoulders'], 'Strengthens the back of the arms.', ['Use a very stable chair against a wall.', 'Keep hips close to the chair and bend elbows backward.', 'Press through the hands to return.'], 'Keep knees bent and use a shallow range.', 'Move feet farther away.', 'Avoid if the front of the shoulder feels pinched.', 'dip'),
    bentRow: ex('Bent-Over Row', 'strength', ['Upper back', 'Arms'], 'Strengthens posture muscles and balances pushing exercises.', ['Hinge at the hips with a long spine.', 'Pull elbows toward the back pockets.', 'Lower the hands slowly without shrugging.'], 'Use water bottles or no weight and squeeze the shoulder blades.', 'Use dumbbells and pause at the top.', 'Do not round the back or jerk the weight.', 'row'),
    reverseFly: ex('Bent-Over Reverse Fly', 'strength', ['Upper back', 'Rear shoulders'], 'Strengthens the muscles that support upright posture.', ['Hinge forward with soft knees.', 'Open the arms out to the sides with a slight elbow bend.', 'Squeeze shoulder blades gently and lower.'], 'Use no weight and a smaller range.', 'Use light dumbbells with slow control.', 'Do not shrug or swing.', 'row'),
    floorPress: ex('Floor Chest Press', 'strength', ['Chest', 'Arms'], 'Builds pushing strength with the floor limiting shoulder depth.', ['Lie on the back with knees bent.', 'Hold dumbbells or water bottles above the elbows.', 'Press upward and lower until upper arms gently touch the floor.'], 'Press one arm at a time with very light weight.', 'Use heavier dumbbells while keeping control.', 'Keep wrists stacked and ribs relaxed.', 'press'),
    superman: ex('Prone Back Extension', 'strength', ['Upper back', 'Glutes'], 'Builds endurance in the back and hip extensors.', ['Lie face down with the neck long.', 'Lift the chest and hands only a small amount.', 'Lower slowly while keeping the glutes gently active.'], 'Lift only the chest or alternate one arm and opposite leg.', 'Add a longer pause at the top.', 'Do not throw the head back or over-arch.', 'superman'),
    plank: ex('Forearm Plank', 'core', ['Core', 'Shoulders'], 'Builds whole-trunk endurance and body alignment.', ['Place elbows under shoulders.', 'Create a long line from head to heels or knees.', 'Brace as if preparing for a gentle punch and breathe normally.'], 'Keep knees on the floor or use an incline.', 'Use a full plank and alternate leg lifts.', 'Do not hold your breath or let the lower back sag.', 'plank'),
    sidePlank: ex('Side Plank', 'core', ['Side core', 'Shoulder'], 'Strengthens the obliques and lateral hip stabilisers.', ['Place elbow below shoulder.', 'Lift the hips and create a straight line through the body.', 'Keep the chest facing forward and breathe.'], 'Keep the lower knee on the floor.', 'Stack the feet and lift the top leg.', 'Do not collapse into the shoulder.', 'sideplank'),
    deadBug: ex('Dead Bug', 'core', ['Deep core', 'Hips'], 'Teaches trunk control while arms and legs move.', ['Lie on the back with arms up and hips and knees bent.', 'Gently brace and lower one heel and the opposite arm.', 'Return before the lower back lifts and alternate.'], 'Move only the legs or tap one heel close to the body.', 'Straighten the moving leg farther.', 'Keep the lower back comfortably supported.', 'deadbug'),
    birdDog: ex('Bird Dog', 'core', ['Core', 'Back', 'Glutes'], 'Improves spinal stability, balance and coordination.', ['Start on hands and knees.', 'Reach one arm forward and the opposite leg back.', 'Keep hips level, return slowly and change sides.'], 'Move only one limb at a time.', 'Pause longer or draw elbow and knee together.', 'Do not rotate the pelvis or overreach.', 'bird'),
    heelTap: ex('Heel Tap Crunch', 'core', ['Abdominals', 'Side core'], 'Builds abdominal endurance with a small controlled movement.', ['Lie on the back with knees bent.', 'Lift shoulder blades slightly and reach toward one heel.', 'Return through centre and alternate sides.'], 'Keep the head down and slide one hand at a time.', 'Move heels farther away.', 'Do not pull the neck forward.', 'crunch'),
    bicycle: ex('Slow Bicycle', 'core', ['Abdominals', 'Obliques'], 'Trains rotation and hip control when performed slowly.', ['Lie on the back and lift the shoulder blades gently.', 'Extend one leg while rotating the ribs toward the opposite knee.', 'Change sides slowly without pulling the neck.'], 'Keep one foot on the floor between repetitions.', 'Straighten the leg lower while maintaining back position.', 'Avoid fast, jerky twisting.', 'crunch'),
    crunch: ex('Controlled Crunch', 'core', ['Abdominals'], 'Strengthens the front of the trunk through a small range.', ['Lie on the back with feet planted.', 'Exhale and lift the shoulder blades slightly.', 'Pause and lower slowly.'], 'Keep the head down and practise abdominal bracing.', 'Hold the top briefly or extend arms overhead.', 'Do not pull the neck or sit all the way up.', 'crunch'),
    lowJack: ex('Low-Impact Jack', 'cardio', ['Heart', 'Legs', 'Shoulders'], 'Raises heart rate without jumping.', ['Step one foot out as arms travel overhead.', 'Bring the foot in as arms lower.', 'Alternate sides at a steady pace.'], 'Keep arms below shoulder height.', 'Progress to a jumping jack.', 'Land softly and keep knees aligned.', 'jack'),
    highKnees: ex('High Knees', 'cardio', ['Hip flexors', 'Quadriceps', 'Core', 'Calves', 'Glutes'], 'Improves cardiovascular fitness, coordination and controlled knee drive.', ['Stand tall with your feet under your hips.', 'Drive one knee toward hip height as the opposite arm moves forward.', 'Land softly under your body and switch sides without leaning back.'], 'March slowly and lift the knees only as high as you can control.', 'Increase the pace while keeping your torso tall and landings quiet.', 'Do not lean backwards, overstride or slam the feet.', 'march'),
    skater: ex('Skater Step', 'cardio', ['Glutes', 'Heart', 'Balance'], 'Develops side-to-side stamina and hip control.', ['Step wide to one side.', 'Bring the other foot behind as a light tap.', 'Push smoothly across to the other side.'], 'Keep the steps small and upright.', 'Add a hop while landing softly.', 'Keep the landing knee tracking over toes.', 'skater'),
    mountainClimber: ex('Mountain Climber', 'cardio', ['Core', 'Shoulders', 'Heart'], 'Combines trunk stability with cardiovascular conditioning.', ['Start in a high plank or incline plank.', 'Drive one knee toward the chest.', 'Switch legs while keeping shoulders over hands.'], 'Use a wall or bench and move slowly.', 'Increase speed without bouncing the hips.', 'Do not let the back sag or hands slide.', 'mountain'),
    fastFeet: ex('Fast Feet', 'cardio', ['Heart', 'Calves', 'Coordination'], 'Improves foot speed and short-burst conditioning.', ['Take a small athletic stance.', 'Make quick, light alternating steps.', 'Keep chest lifted and breathe continuously.'], 'March briskly instead.', 'Add side-to-side travel.', 'Stay light; do not lock the knees.', 'feet'),
    squatReach: ex('Squat to Reach', 'cardio', ['Legs', 'Heart', 'Shoulders'], 'Raises heart rate while training a full-body pattern.', ['Lower into a comfortable squat.', 'Stand and reach arms overhead.', 'Move smoothly and keep knees aligned.'], 'Use a shallow squat and reach forward.', 'Add a calf raise or small jump.', 'Do not rush into poor squat form.', 'squat'),
    reverseLungeKnee: ex('Reverse Lunge to Knee Drive', 'cardio', ['Legs', 'Balance', 'Heart'], 'Builds leg strength, balance and cardiovascular demand.', ['Step back into a controlled lunge.', 'Push through the front foot to stand.', 'Drive the back knee forward before repeating.'], 'Use a toe tap instead of lifting the knee.', 'Add speed or a hop only with excellent control.', 'Keep the standing knee aligned.', 'lunge'),
    burpeeStepback: ex('Step-Back Burpee', 'cardio', ['Full body', 'Heart'], 'Provides full-body conditioning without requiring a jump.', ['Squat and place hands on a stable floor or raised surface.', 'Step feet back to a plank, then step them forward.', 'Stand tall and reach overhead.'], 'Use a wall or bench and omit the plank.', 'Jump feet back and add a small jump at the top.', 'Keep the spine controlled and move at your own pace.', 'burpee'),
    childPose: ex("Child's Pose", 'mobility', ['Back', 'Hips'], 'Gently relaxes the back, hips and shoulders.', ['Start on hands and knees.', 'Sit hips back toward heels.', 'Reach arms forward and breathe slowly.'], 'Place a cushion under the hips or keep hips higher.', 'Walk hands slightly to each side for a side stretch.', 'Use a comfortable knee position and stop if pinching occurs.', 'stretch'),
    catCow: ex('Cat–Cow', 'mobility', ['Spine', 'Core'], 'Moves the spine gently through flexion and extension.', ['Start on hands and knees.', 'Exhale and round the spine comfortably.', 'Inhale and lengthen the chest forward without forcing the lower back.'], 'Use a small range.', 'Add slow hip circles between repetitions.', 'Do not force the neck.', 'catcow'),
    cobra: ex('Low Cobra', 'mobility', ['Chest', 'Abdominals', 'Spine'], 'Opens the front of the body after sitting or core work.', ['Lie face down with hands near the ribs.', 'Press lightly and lengthen the chest forward and up.', 'Keep hips down and lower slowly.'], 'Lift only the chest without pushing the hands.', 'Hold a little longer while breathing comfortably.', 'Avoid compressing the lower back.', 'cobra'),
    hamstringStretch: ex('Hamstring Stretch', 'mobility', ['Hamstrings', 'Calves'], 'Restores comfortable length after leg training.', ['Extend one heel forward with toes up.', 'Hinge from the hips with a long spine.', 'Hold a mild stretch and breathe.'], 'Keep the heel closer and knee slightly bent.', 'Elevate the heel on a low step.', 'Do not bounce or round aggressively.', 'stretch'),
    hipFlexorStretch: ex('Half-Kneeling Hip Flexor Stretch', 'mobility', ['Hip flexors', 'Thighs'], 'Opens the front of the hip after sitting, running or lunging.', ['Kneel with one foot forward and support as needed.', 'Tuck the pelvis gently.', 'Shift forward slightly until the back hip feels a mild stretch.'], 'Perform standing in a split stance.', 'Reach the same-side arm overhead.', 'Do not arch the lower back.', 'lunge'),
    chestOpener: ex('Chest Opener', 'mobility', ['Chest', 'Shoulders'], 'Counters rounded sitting posture and pressing work.', ['Stand tall and place hands behind the back or on the hips.', 'Draw shoulders gently back and down.', 'Lift the breastbone slightly while breathing.'], 'Hold a towel between the hands.', 'Raise clasped hands slightly without shoulder pain.', 'Do not force the shoulders backward.', 'shoulder'),
    figure4: ex('Figure-Four Glute Stretch', 'mobility', ['Glutes', 'Hips'], 'Releases the outer hips and glutes.', ['Sit or lie down and cross one ankle over the opposite thigh.', 'Keep the crossed foot gently flexed.', 'Draw the legs closer until a mild stretch is felt.'], 'Perform seated in a chair.', 'Lie down and draw the supporting thigh closer.', 'Stop if the knee feels pinched.', 'stretch'),
    thoracicRotation: ex('Open-Book Rotation', 'mobility', ['Upper back', 'Chest'], 'Improves upper-back rotation and chest mobility.', ['Lie on one side with hips and knees bent.', 'Reach the top arm across and then open it toward the other side.', 'Follow the hand with the eyes while knees stay together.'], 'Use a smaller arm range.', 'Pause longer in the open position.', 'Do not force the lower back or shoulder.', 'twist'),
    breathing: ex('Slow Recovery Breathing', 'mobility', ['Breathing', 'Nervous system'], 'Helps heart rate settle and reinforces relaxed breathing.', ['Sit or lie comfortably.', 'Inhale gently through the nose.', 'Exhale slowly and allow shoulders and jaw to relax.'], 'Use any comfortable position.', 'Lengthen the exhale slightly without straining.', 'Stop breath holds if dizzy.', 'breathing'),
    downwardDog: ex('Downward Dog Pedal', 'mobility', ['Calves', 'Shoulders', 'Back'], 'Combines shoulder mobility with a moving calf stretch.', ['Start on hands and knees and lift hips.', 'Keep knees bent enough to lengthen the spine.', 'Alternate pressing one heel toward the floor.'], 'Use hands on a wall or bench.', 'Pause longer over each calf.', 'Do not force heels down or collapse shoulders.', 'stretch')
};
const PLANS=[
    plan(1, 'Full Body Foundation', 'Balanced strength and movement control', 'Moderate',
      ['march','armCircles','stepTouch','hipCircles','torsoTwist','heelDigs','kneeHugs','ankleRolls'],
      ['squat','inclinePushup','reverseLunge','birdDog','gluteBridge','shoulderTap'],
      ['goodMorning','pushup','calfRaise','deadBug','superman','plank'],
      ['lowJack','squatReach','highKnees','mountainClimber','skater','fastFeet'],
      ['breathing','childPose','hamstringStretch','hipFlexorStretch','chestOpener','figure4','thoracicRotation','breathing']),
    plan(2, 'Stamina + Core', 'Cardiovascular fitness and trunk endurance', 'Moderate–high',
      ['march','stepTouch','armCircles','heelDigs','torsoTwist','hipCircles','kneeHugs','ankleRolls'],
      ['lowJack','highKnees','skater','mountainClimber','fastFeet','squatReach'],
      ['plank','heelTap','bicycle','birdDog','sidePlank','deadBug'],
      ['fastFeet','highKnees','lowJack','skater','mountainClimber','march'],
      ['breathing','childPose','cobra','hamstringStretch','hipFlexorStretch','figure4','thoracicRotation','breathing']),
    plan(3, 'Lower Body + Glutes', 'Leg strength, hip shape and balance', 'Moderate',
      ['march','heelDigs','stepTouch','hipCircles','kneeHugs','ankleRolls','goodMorning','squat'],
      ['squat','reverseLunge','gluteBridge','calfRaise','wallSit','goodMorning'],
      ['sumoSquat','sideLunge','singleLegBridge','curtsyLunge','donkeyKick','fireHydrant'],
      ['squatPulse','skater','reverseLungeKnee','squatReach','calfRaise','highKnees'],
      ['breathing','childPose','hamstringStretch','hipFlexorStretch','figure4','downwardDog','thoracicRotation','breathing']),
    plan(4, 'Upper Body + Posture', 'Chest, back, shoulders, arms and core', 'Moderate',
      ['march','armCircles','torsoTwist','stepTouch','chestOpener','catCow','shoulderTap','ankleRolls'],
      ['inclinePushup','bentRow','shoulderTap','pikePress','tricepsDip','superman'],
      ['pushup','floorPress','reverseFly','plank','sidePlank','birdDog'],
      ['lowJack','mountainClimber','squatReach','fastFeet','highKnees','burpeeStepback'],
      ['breathing','childPose','catCow','cobra','chestOpener','thoracicRotation','figure4','breathing']),
    plan(5, 'Full Body Conditioning', 'Fat-loss support, stamina and athletic movement', 'High with low-impact options',
      ['march','stepTouch','armCircles','heelDigs','hipCircles','torsoTwist','kneeHugs','squat'],
      ['burpeeStepback','squatReach','mountainClimber','reverseLungeKnee','inclinePushup','highKnees'],
      ['skater','squat','shoulderTap','goodMorning','lowJack','plank'],
      ['fastFeet','burpeeStepback','highKnees','skater','mountainClimber','squatReach'],
      ['breathing','childPose','cobra','hamstringStretch','hipFlexorStretch','chestOpener','figure4','breathing']),
    plan(6, 'Body Sculpt + Mobility', 'Controlled strength, balance and recovery', 'Low–moderate',
      ['march','armCircles','stepTouch','hipCircles','catCow','torsoTwist','kneeHugs','ankleRolls'],
      ['sumoSquat','inclinePushup','gluteBridge','bentRow','birdDog','calfRaise'],
      ['sideLunge','reverseFly','singleLegBridge','deadBug','donkeyKick','sidePlank'],
      ['squatPulse','lowJack','shoulderTap','reverseLungeKnee','fastFeet','march'],
      ['breathing','childPose','catCow','downwardDog','hamstringStretch','hipFlexorStretch','chestOpener','figure4'])
];
const MEALS=[
    meals(1, 'Full Body Foundation', [
      ['Breakfast','🥣','Oats cooked with milk, chia seeds, berries and a spoon of peanut butter.','Vegan: use calcium-fortified soy milk.'],
      ['Snack','🍎','Fruit with Greek yoghurt or a handful of nuts.','Vegan: soy yoghurt or nuts.'],
      ['Lunch','🍛','Dal, brown rice or two wholemeal rotis, mixed salad and lemon.','Add extra lentils or tofu for more protein.'],
      ['Pre-workout','🍌','Banana or wholegrain toast 60–90 minutes before training.','Keep the portion light and easy to digest.'],
      ['Dinner','🥦','Tofu or paneer vegetable stir-fry with quinoa or wholegrain noodles.','Vegan: tofu or tempeh.']
    ]),
    meals(2, 'Stamina + Core', [
      ['Breakfast','🫓','Besan chilla with vegetables and yoghurt.','Vegan: use mint chutney or soy yoghurt.'],
      ['Snack','🥜','Banana with peanut butter.','A useful carbohydrate + fat snack before cardio.'],
      ['Lunch','🫘','Rajma with quinoa or brown rice and cucumber-tomato salad.','Include capsicum or lemon for vitamin C.'],
      ['Recovery','🥛','Milk or fortified soy drink with fruit after training.','Choose unsweetened where practical.'],
      ['Dinner','🍲','Vegetable khichdi with extra moong dal and raita.','Vegan: soy yoghurt raita.']
    ]),
    meals(3, 'Lower Body + Glutes', [
      ['Breakfast','🥣','Greek yoghurt bowl with oats, fruit, pumpkin seeds and walnuts.','Vegan: high-protein soy yoghurt.'],
      ['Snack','🌰','Roasted chickpeas and one piece of fruit.','Prepare with modest salt.'],
      ['Lunch','🫓','Chole, two wholemeal rotis and a large mixed vegetable salad.','Add lemon to improve non-haem iron absorption.'],
      ['Pre-workout','🥔','Small boiled potato, fruit or toast before training.','Carbohydrate supports a demanding leg session.'],
      ['Dinner','🍢','Tofu or paneer tikka bowl with vegetables and brown rice.','Vegan: tofu or tempeh.']
    ]),
    meals(4, 'Upper Body + Posture', [
      ['Breakfast','🍚','Vegetable poha with peas, peanuts and a side of yoghurt.','Vegan: soy yoghurt or extra peas.'],
      ['Snack','🥛','Fortified milk or soy drink with a small handful of nuts.','Check calcium and B12 fortification.'],
      ['Lunch','🍝','Lentil pasta with tomato, spinach and mushrooms.','Top with seeds or a little cheese.'],
      ['Snack','🥕','Hummus with carrots, cucumber and wholegrain crackers.','A simple protein-rich snack.'],
      ['Dinner','🥬','Palak tofu or palak paneer with wholemeal roti and salad.','Vegan: calcium-set tofu.']
    ]),
    meals(5, 'Full Body Conditioning', [
      ['Breakfast','🥣','Overnight oats with milk, chia, banana and cinnamon.','Vegan: fortified soy milk.'],
      ['Pre-workout','🍌','Banana, dates or toast before training.','Avoid a very heavy meal immediately before HIIT.'],
      ['Lunch','🌯','Chickpea salad wrap with hummus, colourful vegetables and wholegrain flatbread.','Add tofu strips for extra protein.'],
      ['Recovery','🥤','Fruit-and-soy smoothie or yoghurt with fruit.','Include a protein source after training.'],
      ['Dinner','🍛','Mixed dal, rice, vegetables and cucumber salad.','Keep oils moderate if fat loss is the goal.']
    ]),
    meals(6, 'Body Sculpt + Mobility', [
      ['Breakfast','🥤','Smoothie with fortified soy or dairy milk, oats, berries and nut butter.','Use whole fruit rather than juice.'],
      ['Snack','🍊','Orange or kiwi with pumpkin seeds.','Vitamin C supports plant-iron absorption.'],
      ['Lunch','🥘','Sambar with idli or dosa and extra vegetables.','Add lentils generously for protein.'],
      ['Snack','🥛','Lassi, soy yoghurt or a small handful of nuts.','Choose unsweetened or lightly sweetened.'],
      ['Dinner','🍲','Vegetable curry with tofu, chickpeas or paneer and a wholegrain side.','Vegan: tofu plus chickpeas.']
    ]),
    meals(7, 'Recovery Day', [
      ['Breakfast','🍞','Wholegrain toast with avocado and eggs or tofu scramble.','Vegan: tofu scramble.'],
      ['Snack','🍐','Fruit and nuts.','Keep hydration steady through the day.'],
      ['Lunch','🥗','Large lentil and grain salad with colourful vegetables and tahini dressing.','Add lemon and herbs.'],
      ['Snack','🥣','Yoghurt or soy yoghurt with seeds.','Choose a fortified option when possible.'],
      ['Dinner','🍲','Vegetable and bean soup with wholegrain bread.','A lighter recovery-day dinner.']
    ])
];
let state=loadState();
let currentPage='home',libraryView='exercises',quickFilter='all',bodyView='front',selectedMuscle='';
let activePlan=null,session=[],stepIndex=0,remaining=60,timerId=null,isPlaying=false,reviewMode=false,deferredInstallPrompt=null,toastTimer=null;
const $=id=>document.getElementById(id);const $$=s=>[...document.querySelectorAll(s)];

function loadState(){
 try{
  let raw=localStorage.getItem(STORAGE_KEY);
  if(!raw){
   const old=localStorage.getItem(OLD_STORAGE_KEY_V3)||localStorage.getItem(OLD_STORAGE_KEY_V2);
   if(old){const p=JSON.parse(old);raw=JSON.stringify({...DEFAULT_STATE,...p,schema:SCHEMA_VERSION,onboardingDone:true,profile:{...DEFAULT_STATE.profile,...(p.profile||{})},duration:Number(p.duration||60),autoplay:p.autoplay||'on',reducedMotion:p.reducedMotion||'off',diet:p.diet==='vegan'?'vegan':(p.diet||'indian')});}
  }
  const parsed=raw?JSON.parse(raw):{};
  const merged={...DEFAULT_STATE,...parsed,profile:{...DEFAULT_STATE.profile,...(parsed.profile||{})},duration:Number(parsed.duration||60)};
  if(!merged.deviceId)merged.deviceId=uid();
  return merged;
 }catch(e){console.warn(e);const fresh=structuredClone(DEFAULT_STATE);fresh.deviceId=uid();return fresh;}
}
function notifyStateSaved(source='local'){
 try{window.dispatchEvent(new CustomEvent('fitness-v4-state-saved',{detail:{source,state:structuredClone(state)}}));}catch{}
}
function saveState(message,{source='local',skipCloud=false}={}){state.schema=SCHEMA_VERSION;state.updatedAt=new Date().toISOString();if(!state.deviceId)state.deviceId=uid();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));applyTheme();renderAll();if(message)showToast(message);if(!skipCloud)notifyStateSaved(source);}
function applyExternalState(incoming,{message='',source='cloud'}={}){
 const next={...DEFAULT_STATE,...(incoming||{}),profile:{...DEFAULT_STATE.profile,...((incoming||{}).profile||{})},schema:SCHEMA_VERSION};
 if(!next.deviceId)next.deviceId=state.deviceId||uid();
 state=next;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));applyTheme();renderAll();if(message)showToast(message);notifyStateSaved(source);
}
function init(){applyTheme();bindEvents();renderAll();$('checkinDate').value=isoDate(new Date());registerServiceWorker();updateNetworkBadge();const params=new URLSearchParams(location.search),requested=params.get('open');showPage(['home','plan','library','meals','progress','settings'].includes(requested)?requested:'home');if(params.get('review')==='highKnees'){state.onboardingDone=true;setTimeout(openHighKneesReview,80);}else if(!state.onboardingDone)setTimeout(()=>openOnboarding(),300);}
function bindEvents(){
 document.addEventListener('click',event=>{const go=event.target.closest('[data-go]');if(go)showPage(go.dataset.go);});
 $$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
 $('headerSettingsBtn').addEventListener('click',()=>showPage('settings'));
 $('startTodayBtn').addEventListener('click',()=>startWorkout(state.currentDay));$('previewTodayBtn').addEventListener('click',()=>showPage('plan'));
 $('todayPreview').addEventListener('click',()=>openExerciseDialog(PLANS[state.currentDay-1].warmup[0]));
 $$('[data-readiness]').forEach(b=>b.addEventListener('click',()=>{state.readiness=b.dataset.readiness;saveState();renderReadiness();}));
 $('resumeWorkoutBtn').addEventListener('click',resumeSavedWorkout);
 $('closeWorkoutBtn').addEventListener('click',stopTimerAndClose);$('playPauseBtn').addEventListener('click',toggleTimer);$('nextStepBtn').addEventListener('click',nextStep);$('prevStepBtn').addEventListener('click',previousStep);
 $('playerInfoBtn').addEventListener('click',()=>openExerciseDialog(session[stepIndex]?.exerciseId));$('easierBtn').addEventListener('click',()=>showToast($('easierCue').textContent));$('harderBtn').addEventListener('click',()=>showToast($('harderCue').textContent));
 $('replaceBtn').addEventListener('click',replaceCurrentExercise);$('addTimeBtn').addEventListener('click',()=>{remaining+=15;renderPlayer();showToast('15 seconds added');});
 $('exerciseSearch').addEventListener('input',renderExerciseLibrary);$('exerciseFilter').addEventListener('change',renderExerciseLibrary);
 $$('[data-library-view]').forEach(b=>b.addEventListener('click',()=>{libraryView=b.dataset.libraryView;renderLibraryViews();}));
 $$('[data-quick-filter]').forEach(b=>b.addEventListener('click',()=>{quickFilter=b.dataset.quickFilter;renderExerciseLibrary();}));
 $$('[data-body-view]').forEach(b=>b.addEventListener('click',()=>{bodyView=b.dataset.bodyView;renderMuscleMap();}));
 $('mealDaySelect').addEventListener('change',renderMeals);$('settingsForm').addEventListener('submit',saveSettingsFromForm);$('safetyAck').addEventListener('change',e=>{state.safetyAck=e.target.checked;saveState('Safety acknowledgement saved');});
 $('checkinForm').addEventListener('submit',saveCheckin);$('testForm').addEventListener('submit',saveTest);$('closeDialogBtn').addEventListener('click',()=>{destroyMedia($('dialogMedia'));$('exerciseDialog').close();});$('exerciseDialog').addEventListener('close',()=>destroyMedia($('dialogMedia')));
 $('installBtn').addEventListener('click',installApp);$('updateBtn').addEventListener('click',checkForUpdate);$('exportBtn').addEventListener('click',exportBackup);$('importInput').addEventListener('change',importBackup);$('resetBtn').addEventListener('click',resetApp);
 $('downloadAllBtn').addEventListener('click',()=>downloadVideos(EXERCISE_IDS,'All anatomy animations'));$('clearVideosBtn').addEventListener('click',clearDownloadedVideos);
 $('onboardingForm').addEventListener('submit',finishOnboarding);
 window.addEventListener('online',updateNetworkBadge);window.addEventListener('offline',updateNetworkBadge);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('installBtn').disabled=false;});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&isPlaying)pauseTimer();});
 $('reviewHighKneesBtn')?.addEventListener('click',openHighKneesReview);
 $$('[data-review-tab]').forEach(button=>button.addEventListener('click',()=>selectReviewTab(button.dataset.reviewTab)));
}
function selectReviewTab(name){$$('[data-review-tab]').forEach(b=>b.classList.toggle('active',b.dataset.reviewTab===name));$$('[data-review-panel]').forEach(p=>p.classList.toggle('active',p.dataset.reviewPanel===name));}
function renderAll(){renderHome();renderPlan();renderLibraryViews();renderMealOptions();renderDietChips();renderMeals();renderProgress();renderSettings();renderMediaPacks();}
function showPage(page){if(page!=='workout')destroyMedia($('exerciseMedia'));currentPage=page;$$('.page').forEach(el=>el.classList.toggle('active',el.dataset.page===page));const navPage=page==='workout'?'plan':page;$$('.nav-btn').forEach(el=>el.classList.toggle('active',el.dataset.go===navPage));document.body.classList.toggle('workout-active',page==='workout'&&!$('workoutPlayer').classList.contains('hidden'));$('mainContent').focus({preventScroll:true});window.scrollTo({top:0,behavior:'auto'});if(page==='settings')updateMediaStorageLabel();}
function renderHome(){
 const p=PLANS[state.currentDay-1]||PLANS[0],summary=workoutSummary(),completed=uniqueCompletedDays().length,pct=Math.round(completed/6*100);
 $('todayTitle').textContent=`Day ${p.day} · ${p.title}`;$('todaySummary').textContent=GOALS[state.goal].note;$('todayDuration').textContent=`${state.duration} minutes`;$('todayIntensity').textContent=p.intensity;$('todayGoalPill').textContent=GOALS[state.goal].label;
 $('weekProgressRing').textContent=`${pct}%`;$('weekScoreRing').style.setProperty('--score',`${pct}%`);$('homeStreak').textContent=summary.streak;$('homeMinutes').textContent=summary.totalMinutes;
 $('todayPoster').src=posterUrl(p.circuitA[0]);$('goalGuideTitle').textContent=GOALS[state.goal].label;$('goalGuideText').textContent=GOALS[state.goal].note;$('goalSteps').innerHTML=GOALS[state.goal].steps.map((x,i)=>`<div class="goal-step"><span>${i+1}</span><div><strong>${x}</strong><p>${goalStepDetail(state.goal,i)}</p></div></div>`).join('');
 const meal=MEALS.find(x=>x.day===state.currentDay)||MEALS[0];$('homeMealPreview').innerHTML=meal.items.slice(0,3).map(x=>`<article><strong>${x[0]}</strong><span>${dietText(x)}</span></article>`).join('');
 $('weekStrip').innerHTML='';for(let day=1;day<=7;day++){const b=document.createElement('button');b.type='button';b.className=`week-day ${day===state.currentDay?'today':''} ${state.completedDays.includes(day)?'done':''} ${day===7?'rest':''}`;b.innerHTML=`<strong>${day===7?'Rest':`D${day}`}</strong><small>${day===7?'Recover':PLANS[day-1].title.split(' ')[0]}</small>`;b.addEventListener('click',()=>day===7?showRecovery():startWorkout(day));$('weekStrip').appendChild(b);}renderReadiness();
}
function renderReadiness(){const map={fresh:'Normal session is suitable if warm-up feels good.',okay:'Use controlled pace and stop one level before poor form.',sore:'Choose easier variations, lower impact and longer recovery.',pain:'Do not train through sharp or worsening pain. Assess the cause first.'};$$('[data-readiness]').forEach(b=>b.classList.toggle('active',b.dataset.readiness===state.readiness));$('readinessAdvice').textContent=map[state.readiness]||'Choose one';}
function renderPlan(){
 $('planSessionLength').textContent=state.duration;$('planDurationNote').textContent=state.duration===60?'Each full session is exactly 60 minutes.':`You selected the ${state.duration}-minute version; the full version remains 60 minutes.`;$('resumeWorkoutBtn').classList.toggle('hidden',!state.activeSession);
 const c=$('planList');c.innerHTML='';PLANS.forEach(p=>{const card=document.createElement('article');card.className=`plan-card ${state.completedDays.includes(p.day)?'completed':''}`;const count=uniqueIdsForPlan(p).length;card.innerHTML=`<div class="day-badge">${state.completedDays.includes(p.day)?'✓':`D${p.day}`}</div><div><h2>${p.title}</h2><p>${p.focus}</p><div class="plan-meta"><span>${state.duration} minutes</span><span>•</span><span>${p.intensity}</span><span>•</span><span>${count} full-body anatomy animations · offline included</span></div></div><div class="plan-actions"><button type="button" class="offline">Animations offline</button><button type="button" class="start">${state.completedDays.includes(p.day)?'Repeat':'Start'}</button></div>`;card.querySelector('.start').addEventListener('click',()=>startWorkout(p.day));card.querySelector('.offline').addEventListener('click',()=>downloadVideos(uniqueIdsForPlan(p),`Day ${p.day} anatomy pack`));c.appendChild(card);});
 const rest=document.createElement('article');rest.className='plan-card';rest.innerHTML=`<div class="day-badge">D7</div><div><h2>Recovery Day</h2><p>Easy walking, gentle mobility, hydration, balanced meals and sufficient sleep.</p><div class="plan-meta"><span>15–45 minutes optional</span><span>•</span><span>No hard intervals</span></div></div><div class="plan-actions"><button type="button" class="start">Open recovery</button></div>`;rest.querySelector('button').addEventListener('click',showRecovery);c.appendChild(rest);
}
function showRecovery(){$('mealDaySelect').value='7';renderMeals();showPage('meals');showToast('Use easy walking or gentle mobility today');}
function renderLibraryViews(){$$('[data-library-view]').forEach(b=>b.classList.toggle('active',b.dataset.libraryView===libraryView));$('exerciseLibraryView').classList.toggle('hidden',libraryView!=='exercises');$('muscleMapView').classList.toggle('hidden',libraryView!=='muscles');if(libraryView==='exercises')renderExerciseLibrary();else renderMuscleMap();}
function renderExerciseLibrary(){
 const q=($('exerciseSearch').value||'').toLowerCase().trim(),cat=$('exerciseFilter').value;cToggleQuick();const entries=Object.entries(EXERCISES).filter(([,x])=>{const hay=`${x.name} ${x.category} ${x.muscles.join(' ')} ${x.benefit}`.toLowerCase();return(cat==='all'||x.category===cat)&&(quickFilter==='all'||hay.includes(quickFilter.toLowerCase()))&&(!q||hay.includes(q));});
 const c=$('exerciseLibrary');c.innerHTML='';entries.forEach(([id,x])=>{const card=document.createElement('article');card.className='exercise-card';card.innerHTML=`<button type="button"><img loading="lazy" src="${posterUrl(id)}" alt="Full-body demonstration of ${escapeHtml(x.name)}"><div class="card-copy"><p class="eyebrow">${x.category.toUpperCase()}</p><h2>${x.name}</h2><p>${x.benefit}</p><span class="video-label">${id==='highKnees'?'▶ Realistic exercise video + target muscle guide':'▶ Built-in guided exercise animation'}</span></div></button>`;card.querySelector('button').addEventListener('click',()=>openExerciseDialog(id));c.appendChild(card);});if(!entries.length)c.innerHTML='<div class="notice"><strong>No matching exercise</strong><p>Try another search or filter.</p></div>';
}
function cToggleQuick(){$$('[data-quick-filter]').forEach(b=>b.classList.toggle('active',b.dataset.quickFilter===quickFilter));}
function renderMuscleMap(){
 $$('[data-body-view]').forEach(b=>b.classList.toggle('active',b.dataset.bodyView===bodyView));$('muscleMap').innerHTML=muscleSvg(bodyView);$$('.muscle-hit').forEach(el=>{el.classList.toggle('active',el.dataset.muscle===selectedMuscle);el.addEventListener('click',()=>selectMuscle(el.dataset.muscle));});if(selectedMuscle)selectMuscle(selectedMuscle,false);
}
function selectMuscle(muscle,rerender=true){selectedMuscle=muscle;const info=MUSCLE_INFO[muscle]||MUSCLE_INFO.full;$('muscleTitle').textContent=info.title;$('muscleDescription').textContent=info.text;const matches=Object.entries(EXERCISES).filter(([,x])=>`${x.muscles.join(' ')}`.toLowerCase().includes(info.term)).slice(0,8);$('muscleExerciseLinks').innerHTML=matches.map(([id,x])=>`<button type="button" class="muscle-link" data-ex="${id}">${x.name}</button>`).join('')||'<p class="muted">Use the exercise search for more options.</p>';$$('[data-ex]').forEach(b=>b.addEventListener('click',()=>openExerciseDialog(b.dataset.ex)));if(rerender)renderMuscleMap();}
const MUSCLE_INFO={full:{title:'Full body',term:'',text:'Select a body area to view matching exercises.'},chest:{title:'Chest',term:'chest',text:'Pushes the arms away from the body and supports upper-body pressing.'},shoulders:{title:'Shoulders',term:'shoulder',text:'Move and stabilise the arms during pressing, raising and carrying.'},arms:{title:'Arms',term:'arms',text:'Biceps and triceps bend and straighten the elbows.'},core:{title:'Core',term:'core',text:'Controls the trunk and transfers force between the upper and lower body.'},back:{title:'Back',term:'back',text:'Supports posture, pulling movements and spinal control.'},glutes:{title:'Glutes',term:'glute',text:'Extend and stabilise the hips during squats, lunges and walking.'},quads:{title:'Quadriceps',term:'thigh',text:'Straighten the knees and contribute strongly to squats and steps.'},hamstrings:{title:'Hamstrings',term:'hamstring',text:'Bend the knees and extend the hips during hinges and bridges.'},calves:{title:'Calves',term:'calf',text:'Support ankle movement, walking, balance and jumping.'},hips:{title:'Hips',term:'hip',text:'Control leg movement in several directions and support balance.'}};
function muscleSvg(view){const back=view==='back';return `<svg viewBox="0 0 480 650" role="img" aria-label="${view} human body muscle map"><g><circle class="muscle-shape" cx="240" cy="58" r="39"/><path class="muscle-shape" d="M205 100 Q240 82 275 100 L300 245 Q275 295 270 330 L210 330 Q205 295 180 245Z"/><path class="muscle-shape" d="M190 115 L125 260 L150 278 L215 160Z"/><path class="muscle-shape" d="M290 115 L355 260 L330 278 L265 160Z"/><path class="muscle-shape" d="M210 325 L165 510 L195 600 L225 590 L238 390Z"/><path class="muscle-shape" d="M270 325 L315 510 L285 600 L255 590 L242 390Z"/>
 ${back?`<ellipse class="muscle-hit" data-muscle="back" cx="240" cy="182" rx="58" ry="75"/><ellipse class="muscle-hit" data-muscle="shoulders" cx="190" cy="128" rx="30" ry="24"/><ellipse class="muscle-hit" data-muscle="shoulders" cx="290" cy="128" rx="30" ry="24"/>`:`<ellipse class="muscle-hit" data-muscle="chest" cx="240" cy="158" rx="55" ry="42"/><ellipse class="muscle-hit" data-muscle="shoulders" cx="190" cy="126" rx="28" ry="24"/><ellipse class="muscle-hit" data-muscle="shoulders" cx="290" cy="126" rx="28" ry="24"/>`}
 <ellipse class="muscle-hit" data-muscle="arms" cx="153" cy="215" rx="24" ry="62"/><ellipse class="muscle-hit" data-muscle="arms" cx="327" cy="215" rx="24" ry="62"/><ellipse class="muscle-hit" data-muscle="core" cx="240" cy="247" rx="42" ry="63"/><ellipse class="muscle-hit" data-muscle="glutes" cx="240" cy="340" rx="53" ry="35"/><ellipse class="muscle-hit" data-muscle="quads" cx="205" cy="430" rx="27" ry="78"/><ellipse class="muscle-hit" data-muscle="quads" cx="275" cy="430" rx="27" ry="78"/><ellipse class="muscle-hit" data-muscle="hamstrings" cx="210" cy="455" rx="24" ry="67"/><ellipse class="muscle-hit" data-muscle="hamstrings" cx="270" cy="455" rx="24" ry="67"/><ellipse class="muscle-hit" data-muscle="calves" cx="190" cy="555" rx="23" ry="53"/><ellipse class="muscle-hit" data-muscle="calves" cx="290" cy="555" rx="23" ry="53"/><ellipse class="muscle-hit" data-muscle="hips" cx="240" cy="326" rx="67" ry="24"/></g></svg>`;}
function renderMealOptions(){const s=$('mealDaySelect');if(s.options.length)return;MEALS.forEach(m=>{const o=document.createElement('option');o.value=m.day;o.textContent=`Day ${m.day}: ${m.focus}`;s.appendChild(o);});s.value=state.currentDay;}
function renderDietChips(){$('dietModeChips').innerHTML=Object.entries(DIET_LABELS).map(([id,label])=>`<button type="button" data-diet="${id}" class="${state.diet===id?'active':''}">${label}</button>`).join('');$$('[data-diet]').forEach(b=>b.addEventListener('click',()=>{state.diet=b.dataset.diet;saveState('Diet style updated');}));}
function renderMeals(){const selected=Number($('mealDaySelect').value||state.currentDay),mp=MEALS.find(m=>m.day===selected)||MEALS[0],c=$('mealCards');c.innerHTML='';mp.items.forEach((x,i)=>{const card=document.createElement('article');card.className='meal-card';card.innerHTML=`<div class="meal-icon">${x[1]}</div><div><p class="eyebrow">${x[0].toUpperCase()}</p><h2>${dietText(x)}</h2><small>${mealNote(x)}</small></div><button type="button">Replace</button>`;card.querySelector('button').addEventListener('click',()=>showToast(mealReplacement(x[0])));c.appendChild(card);});$('proteinFocus').textContent=state.diet==='highProtein'?'Include a substantial protein source at every meal':'Include a protein source at every main meal';$('timingTip').textContent=selected===7?'Recovery day: balanced meals and steady hydration':'Light carbohydrate snack 60–90 minutes before training';}
function dietText(x){if(state.diet==='vegan')return x[3].replace(/^Vegan:\s*/i,'')||x[2];if(state.diet==='highProtein')return `${x[2]} Add tofu, lentils, Greek/soy yoghurt or another suitable protein.`;if(state.diet==='ovo')return `${x[2]} Eggs can be used as a protein replacement where suitable.`;return x[2];}
function mealNote(x){const exclusion=state.foodExclusions?` Exclude: ${state.foodExclusions}.`:'';return `${DIET_LABELS[state.diet]}. ${x[3]}${exclusion}`;}
function mealReplacement(type){const r={Breakfast:'Try moong dal chilla, tofu scramble or high-protein oats.',Lunch:'Try rajma, chole, lentil pasta or tofu grain bowl.',Dinner:'Try dal, tofu curry, tempeh stir-fry or bean soup.',Snack:'Try fruit with soy yoghurt, nuts or roasted chickpeas.','Pre-workout':'Try banana, toast, dates or a small potato.','Recovery':'Try fortified soy milk, yoghurt, tofu meal or lentil dish.'};return r[type]||'Choose another balanced meal with vegetables, whole grains and a protein source.';}
function renderProgress(){const s=workoutSummary();$('progressWorkouts').textContent=state.workouts.length;$('progressMinutes').textContent=s.totalMinutes;$('progressStreak').textContent=s.streak;const week=programWeek(),idx=Math.min(5,Math.floor((week-1)/2));$('progressStage').textContent=idx+1;$('stageTitle').textContent=`${STAGES[idx].name} · ${STAGES[idx].weeks}`;$('stageBadge').textContent=`Stage ${idx+1} of 6`;$('stageText').textContent=STAGES[idx].text;const pct=Math.min(100,Math.round(week/12*100));$('programProgressBar').style.width=`${pct}%`;$('programProgressText').textContent=`Program week ${week} of 12 · ${pct}% of the cycle`;
 renderHistory('checkinHistory',state.checkins,(x)=>[x.weight?`${x.weight} kg`:'',x.waist?`${x.waist} cm waist`:'',x.pulse?`${x.pulse} bpm`:'',x.notes||''].filter(Boolean).join(' · '),'checkin');renderHistory('testHistory',state.tests,x=>`${testLabel(x.type)}: ${x.value}`,'test');}
function renderHistory(id,items,text,type){const c=$(id);c.innerHTML='';const sorted=[...items].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12);if(!sorted.length){c.innerHTML='<p class="muted">No records saved yet.</p>';return;}sorted.forEach(x=>{const row=document.createElement('article');row.className='history-item';row.innerHTML=`<div class="history-date">${formatDate(x.date)}</div><div class="history-values">${escapeHtml(text(x))}</div><button type="button" aria-label="Delete">×</button>`;row.querySelector('button').addEventListener('click',()=>{state[type==='test'?'tests':'checkins']=state[type==='test'?'tests':'checkins'].filter(y=>y.id!==x.id);saveState('Record deleted');});c.appendChild(row);});}
function renderSettings(){const p=state.profile;$('profileName').value=p.name;$('ageRange').value=p.ageRange;$('profileHeight').value=p.height;$('profileWeight').value=p.weight;$('goalSelect').value=state.goal;$('levelSelect').value=state.level;$('durationSelect').value=String(state.duration);$('equipmentSelect').value=state.equipment;$('dietSelect').value=state.diet;$('foodExclusions').value=state.foodExclusions;$('themeSelect').value=state.theme;$('soundSelect').value=state.sound;$('autoplaySelect').value=state.autoplay;$('motionSelect').value=state.reducedMotion;$('safetyAck').checked=state.safetyAck;$('appVersion').textContent=APP_VERSION;}
function saveSettingsFromForm(e){e.preventDefault();state.profile={name:$('profileName').value.trim(),ageRange:$('ageRange').value,height:$('profileHeight').value,weight:$('profileWeight').value};state.goal=$('goalSelect').value;state.level=$('levelSelect').value;state.duration=Number($('durationSelect').value);state.equipment=$('equipmentSelect').value;state.diet=$('dietSelect').value;state.foodExclusions=$('foodExclusions').value.trim();state.theme=$('themeSelect').value;state.sound=$('soundSelect').value;state.autoplay=$('autoplaySelect').value;state.reducedMotion=$('motionSelect').value;saveState('Settings saved');}
function saveCheckin(e){e.preventDefault();const item={id:uid(),date:$('checkinDate').value,updatedAt:new Date().toISOString(),weight:$('checkinWeight').value,waist:$('checkinWaist').value,pulse:$('checkinPulse').value,notes:$('checkinNotes').value.trim()};if(!item.date)return showToast('Choose a date');if(!item.weight&&!item.waist&&!item.pulse&&!item.notes)return showToast('Add at least one value');state.checkins.push(item);e.target.reset();$('checkinDate').value=isoDate(new Date());saveState('Check-in saved');}
function saveTest(e){e.preventDefault();const value=$('testValue').value;if(value==='')return;state.tests.push({id:uid(),date:isoDate(new Date()),updatedAt:new Date().toISOString(),type:$('testType').value,value});e.target.reset();saveState('Fitness result saved');}
function testLabel(x){return{march2:'2-minute march',plank:'Plank hold',pushups:'Controlled push-ups',squats:'Chair squats'}[x]||x;}
function startWorkout(day){const p=PLANS.find(x=>x.day===day);if(!p)return;reviewMode=false;activePlan=p;session=buildSession(p,state.duration);stepIndex=0;remaining=session[0].duration;isPlaying=false;clearInterval(timerId);state.activeSession={day,stepIndex,remaining,duration:state.duration,startedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};persistOnly();notifyStateSaved('local');$('workoutEmpty').classList.add('hidden');$('workoutPlayer').classList.remove('hidden');showPage('workout');renderPlayer();if(!state.safetyAck)showToast('Please review the safety acknowledgement in Settings');}
function resumeSavedWorkout(){const s=state.activeSession;if(!s)return;reviewMode=false;const p=PLANS.find(x=>x.day===s.day);if(!p){state.activeSession=null;return;}activePlan=p;session=buildSession(p,s.duration||state.duration);stepIndex=Math.min(s.stepIndex,session.length-1);remaining=s.remaining||session[stepIndex].duration;$('workoutEmpty').classList.add('hidden');$('workoutPlayer').classList.remove('hidden');showPage('workout');renderPlayer();}
function openHighKneesReview(){pauseTimer();reviewMode=true;activePlan=PLANS[0];session=[step('highKnees','Cardio technique review',60,'interval')];stepIndex=0;remaining=60;isPlaying=false;$('workoutEmpty').classList.add('hidden');$('workoutPlayer').classList.remove('hidden');showPage('workout');renderPlayer();selectReviewTab('how');}
function buildSession(p,duration){const out=[];const add=(ids,phase,rounds=1)=>{for(let r=1;r<=rounds;r++)ids.forEach(id=>out.push(step(id,rounds>1?`${phase} · Round ${r}/${rounds}`:phase,60,'interval')));};if(duration===30){p.warmup.slice(0,5).forEach(id=>out.push(step(id,'Warm-up',60,'continuous')));add(p.circuitA,'Main circuit',2);add(p.circuitB,'Strength circuit',1);add(p.finisher.slice(0,3),'Finisher',1);p.cooldown.slice(0,4).forEach(id=>out.push(step(id,'Cool-down',60,'continuous')));}else if(duration===45){p.warmup.slice(0,6).forEach(id=>out.push(step(id,'Warm-up',60,'continuous')));add(p.circuitA,'Circuit A',2);out.push({exerciseId:null,name:'Hydration + transition',phase:'Transition',duration:60,mode:'transition'});add(p.circuitB,'Circuit B',2);add(p.finisher,'Finisher',1);p.cooldown.slice(0,8).forEach(id=>out.push(step(id,'Cool-down',60,'continuous')));}else{p.warmup.forEach(id=>out.push(step(id,'Warm-up',60,'continuous')));add(p.circuitA,'Circuit A',3);out.push({exerciseId:null,name:'Hydration + transition',phase:'Two-minute transition',duration:120,mode:'transition'});add(p.circuitB,'Circuit B',3);add(p.finisher,'Six-minute finisher',1);p.cooldown.forEach(id=>out.push(step(id,'Cool-down',60,'continuous')));}return out;}
function step(id,phase,duration,mode){return{exerciseId:id,name:EXERCISES[id].name,phase,duration,mode};}
function renderPlayer(){const cur=session[stepIndex];if(!cur)return;const progress=((stepIndex+(1-remaining/cur.duration))/session.length)*100;const rest=cur.mode==='interval'&&remaining<=restSeconds();$('playerDay').textContent=`DAY ${activePlan.day}`;$('phaseLabel').textContent=cur.phase;$('stepCounter').textContent=`${stepIndex+1} of ${session.length}`;$('sessionProgressBar').style.width=`${progress}%`;$('timerState').classList.toggle('rest',rest||cur.mode==='transition');$('timerState').textContent=cur.mode==='transition'?'RECOVER':rest?'REST / CHANGE':cur.phase==='Cool-down'?'STRETCH':'MOVE';$('timerDisplay').textContent=formatTime(remaining);$('intervalHint').textContent=cur.mode==='interval'?`${60-restSeconds()} sec movement · ${restSeconds()} sec change`:'Move slowly with controlled breathing';$('playPauseBtn').textContent=isPlaying?'❚❚':'▶';
 if(cur.exerciseId){const x=EXERCISES[cur.exerciseId];renderMedia($('exerciseMedia'),cur.exerciseId,true);$('playerWorkoutTitle').textContent=x.name;$('playerWorkoutSub').textContent=x.name==='High Knees'?'Cardio · Full Body':`${categoryDisplay(x.category)} · ${activePlan.title}`;$('exerciseCategory').textContent=x.category.toUpperCase();$('exerciseName').textContent=x.name;$('exerciseCue').textContent=`${x.steps[0]} ${x.steps[1]||''}`.trim();$('targetMuscles').innerHTML=x.muscles.map(m=>`<span>${m}</span>`).join('');$('easierCue').textContent=x.easier;$('harderCue').textContent=x.harder;$('playerInfoBtn').disabled=false;updateFinalPlayerCards(x,cur);}else{renderMedia($('exerciseMedia'),'breathing',true);$('playerWorkoutTitle').textContent='Recovery';$('playerWorkoutSub').textContent=activePlan.title;$('exerciseCategory').textContent='RECOVERY';$('exerciseName').textContent='Hydration + transition';$('exerciseCue').textContent='Sip water, breathe slowly and prepare for the next circuit.';$('targetMuscles').innerHTML='<span>Recovery</span><span>Hydration</span>';$('easierCue').textContent='Walk slowly and focus on breathing.';$('harderCue').textContent='Keep recovery easy so the next circuit stays controlled.';$('playerInfoBtn').disabled=true;updateFinalPlayerCards(null,cur);} 
 if(!reviewMode){state.activeSession={day:activePlan.day,stepIndex,remaining,duration:state.duration,startedAt:state.activeSession?.startedAt||new Date().toISOString()};persistOnly();}}
function categoryDisplay(cat){return({warmup:'Warm-up Exercise',strength:'Strength Exercise',cardio:'Cardio Exercise',core:'Core Exercise',mobility:'Mobility Exercise'})[cat]||'Exercise';}
function recommendationForExercise(x){
 const change=restSeconds(),work=60-change;
 if(!x)return{primaryLabel:'Recovery',primary:'Easy',secondaryLabel:'Time',secondary:'1–2 min',tertiaryLabel:'Focus',tertiary:'Breathe',rest:'Use the full transition time.',tips:['Walk gently','Sip water','Prepare for the next circuit'],position:'Recovery'};
 if(x.category==='strength')return{primaryLabel:'Reps',primary:'10–15',secondaryLabel:'Sets',secondary:'3',tertiaryLabel:'Rest',tertiary:'30–60 sec',rest:'Rest for 30–60 seconds between controlled sets.',tips:['Keep your core gently braced','Move with control','Use only a pain-free range'],position:'Working position'};
 if(x.category==='cardio')return{primaryLabel:'Work',primary:`${work} sec`,secondaryLabel:'Rounds',secondary:'2–3',tertiaryLabel:'Change',tertiary:`${change} sec`,rest:`Use the ${change}-second change period before the next interval.`,tips:['Keep your torso tall','Land quietly under your body','Slow down before your form changes'],position:x.name==='High Knees'?'Knee drive':'Action position'};
 if(x.category==='core')return{primaryLabel:'Reps',primary:'8–14',secondaryLabel:'Sets',secondary:'2–3',tertiaryLabel:'Rest',tertiary:'30–45 sec',rest:'Rest for 30–45 seconds between sets.',tips:['Brace the trunk gently','Keep the neck relaxed','Stop if the lower back strains'],position:'Control position'};
 if(x.category==='mobility')return{primaryLabel:'Hold',primary:'20–30 sec',secondaryLabel:'Sets',secondary:'2',tertiaryLabel:'Change',tertiary:'Slowly',rest:'Breathe and change sides slowly.',tips:['Do not force the stretch','Move slowly','Stay in a comfortable range'],position:'Stretch position'};
 return{primaryLabel:'Time',primary:'30 sec',secondaryLabel:'Sets',secondary:'2',tertiaryLabel:'Rest',tertiary:'15–30 sec',rest:'Rest briefly and continue only with controlled movement.',tips:['Move smoothly','Breathe comfortably','Stay tall and relaxed'],position:'Start position'};
}
function updateFinalPlayerCards(x,cur){
 const steps=x?.steps||['Walk gently, sip water and breathe slowly.','Relax your shoulders and slow your breathing.','Prepare for the next exercise when ready.'];
 const id=x?Object.entries(EXERCISES).find(([,v])=>v===x)?.[0]||'breathing':'breathing',rec=recommendationForExercise(x);
 $('finalStepBadge').textContent=`${steps.length} steps`;$('finalStepTitle').textContent=x?'How to move':'Recovery';$('finalStepText').textContent=steps[0]||'';$('reviewStepTwo').textContent=steps[1]||'';$('reviewStepThree').textContent=steps[2]||'';
 $('finalAltLabel').textContent=x?.name==='High Knees'?'Other side':steps[1]||'Next position';$('finalAltImage').src=posterUrl(id);$('finalPositionLabel').textContent=rec.position;
 $('reviewPrimaryLabel').textContent=rec.primaryLabel;$('finalRepsText').textContent=rec.primary;$('reviewSecondaryLabel').textContent=rec.secondaryLabel;$('finalSetsText').textContent=rec.secondary;$('reviewTertiaryLabel').textContent=rec.tertiaryLabel;$('reviewRestCompact').textContent=rec.tertiary;$('finalRestText').textContent=rec.rest;
 $('finalTipA').textContent=rec.tips[0]||'';$('finalTipB').textContent=rec.tips[1]||'';$('finalTipC').textContent=x?x.caution||rec.tips[2]:rec.tips[2]||'';
 const muscle=$('reviewMuscleImage');if(id==='highKnees'){muscle.src='assets/muscles/highKnees.svg';muscle.alt='High Knees target muscles: core, hip flexors, quadriceps and calves';}else{muscle.src='assets/ui/anatomy-motion-poster.svg';muscle.alt=`Target areas for ${x?.name||'recovery'}`;}
 $('finalAltPreview').onclick=()=>openExerciseDialog(cur?.exerciseId||'breathing');
}
function destroyMedia(container){if(!container)return;try{container.__anatomyMotion?.destroy?.();}catch{}try{container.__video?.pause?.();}catch{}container.__anatomyMotion=null;container.__video=null;delete container.dataset.mediaId;container.innerHTML='';}
function renderMedia(container,id,autoplay){
 const x=EXERCISES[id]||EXERCISES.breathing;
 const shouldPlay=autoplay&&state.autoplay==='on'&&state.reducedMotion!=='on';
 const hasVideo=!!videoUrl(id);
 if(container.dataset.mediaId===id&&((hasVideo&&container.querySelector('video'))||(!hasVideo&&container.__anatomyMotion)))return;
 destroyMedia(container);
 container.dataset.mediaId=id;
 if(hasVideo){
  container.innerHTML=`<video playsinline muted loop preload="metadata" poster="${posterUrl(id)}"><source src="${videoUrl(id)}" type="video/mp4"></video>`;
  const video=container.querySelector('video');
  if(shouldPlay) video.play().catch(()=>{});
  const controls=document.createElement('div');controls.className='media-controls';controls.innerHTML=`<button type="button" data-media-action="toggle">${shouldPlay?'Pause':'Play'}</button>`;container.appendChild(controls);
  const b=controls.querySelector('button');b.addEventListener('click',()=>{if(video.paused){video.play().catch(()=>{});b.textContent='Pause';}else{video.pause();b.textContent='Play';}});
  container.__video=video;
  return;
 }
 if(!window.AnatomyMotion){
  container.innerHTML=`<div class="v4-media-pending"><img src="${posterUrl(id)}" alt="Exercise demonstration of ${escapeHtml(x.name)}"><div><strong>${escapeHtml(x.name)}</strong><span>Exercise media is loading.</span></div></div>`;
  return;
 }
 const controller=window.AnatomyMotion.mount(container,id,{name:x.name,muscles:x.muscles,autoplay:shouldPlay});
 const controls=document.createElement('div');controls.className='media-controls';controls.innerHTML=`<button type="button" data-media-action="toggle">${shouldPlay?'Pause':'Play'}</button>`;container.appendChild(controls);
 const b=controls.querySelector('button');b.addEventListener('click',()=>{const playing=controller.toggle();b.textContent=playing?'Pause':'Play';});
}
function toggleTimer(){isPlaying?pauseTimer():playTimer();}function playTimer(){if(!session.length)return;isPlaying=true;$('exerciseMedia')?.__video?.play?.().catch(()=>{});$('exerciseMedia')?.__anatomyMotion?.play?.();beep(720,.07);clearInterval(timerId);timerId=setInterval(()=>{remaining--;if(remaining===restSeconds()&&session[stepIndex].mode==='interval')beep(540,.1);if(remaining<=0){beep(880,.12);advanceStepAutomatically();}else renderPlayer();},1000);renderPlayer();}function pauseTimer(){isPlaying=false;clearInterval(timerId);timerId=null;$('exerciseMedia')?.__video?.pause?.();$('exerciseMedia')?.__anatomyMotion?.pause?.();renderPlayer();}
function nextStep(){pauseTimer();if(reviewMode){showToast('High Knees review screen');return;}if(stepIndex>=session.length-1)return completeWorkout();stepIndex++;remaining=session[stepIndex].duration;renderPlayer();notifyStateSaved('local');}function previousStep(){pauseTimer();if(reviewMode){showToast('High Knees review screen');return;}stepIndex=Math.max(0,stepIndex-1);remaining=session[stepIndex].duration;renderPlayer();notifyStateSaved('local');}function advanceStepAutomatically(){if(state.autoAdvance==='off'){pauseTimer();remaining=0;renderPlayer();showToast('Exercise complete — tap Next when ready');notifyStateSaved('local');return;}if(stepIndex>=session.length-1){pauseTimer();completeWorkout();return;}stepIndex++;remaining=session[stepIndex].duration;renderPlayer();notifyStateSaved('local');if(!isPlaying)playTimer();}
function completeWorkout(){pauseTimer();const day=activePlan.day,now=new Date();state.completedDays=[...new Set([...state.completedDays,day])].sort();state.currentDay=day<6?day+1:1;state.workouts.push({id:uid(),date:isoDate(now),timestamp:now.toISOString(),updatedAt:now.toISOString(),day,title:activePlan.title,minutes:state.duration,goal:state.goal,level:state.level});if(!state.programStart)state.programStart=isoDate(now);state.activeSession=null;saveState('Workout completed — excellent consistency');$('workoutPlayer').classList.add('hidden');$('workoutEmpty').classList.remove('hidden');showPage('progress');}
function stopTimerAndClose(){pauseTimer();reviewMode=false;$('workoutPlayer').classList.add('hidden');$('workoutEmpty').classList.remove('hidden');showPage('plan');}
function restSeconds(){return state.level==='advanced'?10:state.level==='intermediate'?15:25;}
function replaceCurrentExercise(){const cur=session[stepIndex];if(!cur?.exerciseId)return;const x=EXERCISES[cur.exerciseId];const candidates=Object.entries(EXERCISES).filter(([id,y])=>id!==cur.exerciseId&&y.category===x.category&&y.muscles.some(m=>x.muscles.includes(m)));if(!candidates.length)return showToast('No similar replacement found');const[id,y]=candidates[Math.floor(Math.random()*candidates.length)];cur.exerciseId=id;cur.name=y.name;renderPlayer();showToast(`Replaced with ${y.name}`);}
function openExerciseDialog(id){const x=EXERCISES[id];if(!x)return;renderMedia($('dialogMedia'),id,true);$('dialogCategory').textContent=x.category.toUpperCase();$('dialogTitle').textContent=x.name;$('dialogTags').innerHTML=x.muscles.map(m=>`<span>${m}</span>`).join('');$('dialogBenefit').textContent=x.benefit;$('dialogSteps').innerHTML=x.steps.map(s=>`<li>${s}</li>`).join('');$('dialogBreathing').textContent=breathingCue(x.category,x.name);$('dialogEasier').textContent=x.easier;$('dialogHarder').textContent=x.harder;$('dialogCaution').textContent=x.caution;$('exerciseDialog').showModal();}
function breathingCue(cat,name){if(cat==='strength'||cat==='core')return`Breathe out through the effort and breathe in during the easier return. Never hold your breath to force ${name}.`;if(cat==='cardio')return'Use a pace that allows controlled, regular breathing. Reduce impact before technique becomes rushed.';return'Breathe slowly and never force a painful range.';}
function renderMediaPacks(){const c=$('mediaPackGrid');c.innerHTML='';PLANS.forEach(p=>{const ids=uniqueIdsForPlan(p),d=document.createElement('article');d.className='media-pack';d.innerHTML=`<strong>Day ${p.day}</strong><span>${ids.length} built-in anatomy animations</span><button type="button">Confirm offline</button>`;d.querySelector('button').addEventListener('click',()=>downloadVideos(ids,`Day ${p.day} anatomy pack`));c.appendChild(d);});}
async function downloadVideos(ids,label){$('downloadProgress').classList.remove('hidden');$('downloadProgressBar').style.width='100%';$('downloadProgressText').textContent=`${label}: included in the app and ready offline`;showToast(`${label} is already available offline`);updateMediaStorageLabel();}
async function clearDownloadedVideos(){showToast('The built-in anatomy animations are part of the app and cannot be removed separately');}
async function updateMediaStorageLabel(){if($('mediaStorageLabel'))$('mediaStorageLabel').textContent=`All ${APPROVED_MEDIA.size} animations offline`;}

function uniqueIdsForPlan(p){return[...new Set([...p.warmup,...p.circuitA,...p.circuitB,...p.finisher,...p.cooldown])];}
function finishOnboarding(e){e.preventDefault();state.profile.name=$('onboardName').value.trim();state.goal=$('onboardGoal').value;state.level=$('onboardLevel').value;state.duration=Number($('onboardDuration').value);state.diet=$('onboardDiet').value;state.safetyAck=$('onboardSafety').checked;state.onboardingDone=true;state.programStart=isoDate(new Date());$('onboardingDialog').close();saveState('Your program is ready');}
function openOnboarding(){if(typeof $('onboardingDialog').showModal==='function')$('onboardingDialog').showModal();else state.onboardingDone=true;}
function goalStepDetail(goal,i){const details={general:['Builds whole-body capacity.','Supports heart and lung fitness.','Helps repeat training safely.'],fat:['Preserves and builds useful muscle.','Raises sustainable weekly movement.','Supports gradual energy balance.'],stamina:['Reduces unnecessary joint impact.','Builds duration without rushing.','Shows improvement beyond body weight.'],shape:['Develops balanced proportions.','Increases muscular control.','Shows practical changes over time.'],strength:['Makes load safer and measurable.','Shows progressive overload.','Allows muscles and joints to adapt.'],mobility:['Keeps joints moving regularly.','Builds usable range, not passive range only.','Reduces pressure to force stretching.']};return(details[goal]||details.general)[i];}
function workoutSummary(){const total=state.workouts.reduce((s,x)=>s+Number(x.minutes||0),0),today=new Date(),weekStart=new Date(today);weekStart.setDate(today.getDate()-6);const weekCount=state.workouts.filter(x=>new Date(x.date+'T00:00:00')>=weekStart).length;const dates=[...new Set(state.workouts.map(x=>x.date))].sort().reverse();let streak=0,cursor=new Date();for(let i=0;i<370;i++){const key=isoDate(cursor);if(dates.includes(key)){streak++;cursor.setDate(cursor.getDate()-1);}else if(i===0){cursor.setDate(cursor.getDate()-1);}else break;}return{totalMinutes:total,weekCount,streak};}
function uniqueCompletedDays(){return[...new Set(state.completedDays.filter(x=>x>=1&&x<=6))];}
function programWeek(){if(!state.programStart)return 1;const diff=Math.max(0,Date.now()-new Date(state.programStart+'T00:00:00').getTime());return Math.min(12,Math.floor(diff/604800000)+1);}
function applyTheme(){const dark=state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.style.colorScheme=dark?'dark':'light';}
function updateNetworkBadge(){const b=$('networkBadge');b.textContent=navigator.onLine?'Online':'Offline ready';b.classList.toggle('online',navigator.onLine);}
function registerServiceWorker(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);}
async function checkForUpdate(){if(!('serviceWorker'in navigator))return showToast('Update checking is unavailable');const reg=await navigator.serviceWorker.getRegistration();if(reg){await reg.update();showToast('Update check complete');if(reg.waiting&&confirm('An update is ready. Reload now?')){reg.waiting.postMessage({type:'SKIP_WAITING'});location.reload();}}else showToast('App is current');}
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;}else showToast('On iPhone Safari: Share → Add to Home Screen');}
function exportBackup(){const blob=new Blob([JSON.stringify({app:'Fitness V6.1',version:APP_VERSION,schema:SCHEMA_VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fitness-v6-1-backup-${isoDate(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function importBackup(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result),incoming=p.state||p;if(!incoming.workouts||!incoming.checkins)throw new Error('Invalid');state={...DEFAULT_STATE,...incoming,profile:{...DEFAULT_STATE.profile,...(incoming.profile||{})},schema:SCHEMA_VERSION,onboardingDone:true};saveState('Backup imported');}catch{showToast('This backup could not be imported');}e.target.value='';};r.readAsText(file);}
function resetApp(){if(!confirm('Reset profile, workout history, meals and progress? Downloaded videos will remain.'))return;state=structuredClone(DEFAULT_STATE);localStorage.removeItem(STORAGE_KEY);saveState('App data reset');openOnboarding();}
function persistOnly(){state.updatedAt=new Date().toISOString();if(!state.deviceId)state.deviceId=uid();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function videoUrl(id){return id==='highKnees'?'assets/videos/highKnees-clean.mp4':'';}function posterUrl(id){return id==='highKnees'?'assets/posters/highKnees-clean.jpg':'assets/ui/anatomy-motion-poster.svg';}
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;}function isoDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);}function formatDate(s){return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(s+'T00:00:00'));}function formatTime(n){n=Math.max(0,n);return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function beep(freq,dur){if(state.sound!=='on')return;try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.05,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+dur);o.onended=()=>ctx.close();}catch{}}
function showToast(msg){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
window.FitnessV4API={
 getState:()=>structuredClone(state),
 applyExternalState,
 save:message=>saveState(message),
 setPreference:(key,value)=>{if(!(key in DEFAULT_STATE))return;state[key]=value;saveState('Setting saved');},
 getExercise:id=>EXERCISES[id]?structuredClone(EXERCISES[id]):null,
 getExercises:()=>structuredClone(EXERCISES),
 getPlans:()=>structuredClone(PLANS),
 buildSessionForDay:(day,duration)=>{const p=PLANS.find(x=>x.day===day);return p?structuredClone(buildSession(p,Number(duration||state.duration))):[];},
 getCurrentExerciseId:()=>session[stepIndex]?.exerciseId||null,
 getCurrentStep:()=>({index:stepIndex,total:session.length,remaining,isPlaying,step:session[stepIndex]?structuredClone(session[stepIndex]):null,next:session[stepIndex+1]?structuredClone(session[stepIndex+1]):null}),
 mediaApproved:id=>APPROVED_MEDIA.has(id),
 showToast,
 openExercise:id=>openExerciseDialog(id),
 startWorkout
};
window.FitnessV5API=window.FitnessV4API;
init();
})();